"""rename_google_id_to_oauth_id_and_allow_non_unique_username

Revision ID: 60280a11fb03
Revises: 7b75c3de8920
Create Date: 2026-02-19 04:21:13.016161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60280a11fb03'
down_revision: Union[str, Sequence[str], None] = '7b75c3de8920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users', postgresql_using='lsm')
    op.drop_index(op.f('ix_users_username'), table_name='users', postgresql_using='lsm')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True, postgresql_using='lsm')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True, postgresql_using='lsm')
    op.drop_column('users', 'oauth_id')
    # ### end Alembic commands ###
