"""add_assigned_lane_to_game

Revision ID: 7b75c3de8920
Revises: d72e0788541e
Create Date: 2026-02-19 03:48:21.280191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b75c3de8920'
down_revision: Union[str, Sequence[str], None] = 'd72e0788541e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('assigned_lane', sa.Integer(), nullable=True))
    op.alter_column('users', 'is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('games', 'assigned_lane')
    # ### end Alembic commands ###
